/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import atomics.User;
import corecliente.GlobalClient;
import java.awt.Color;
import principal.Status;
import principal.OurFonts;

/**
 *
 * @author Geeo
 */
public class CabecalhoPanel extends javax.swing.JPanel {

    /**
     * Creates new form CabecalhoPanel
     */
    public CabecalhoPanel() {
        initComponents();
    }

    public CabecalhoPanel(User user) {
        initComponents();
        this.lbHi.setText("Hi " + user.getNickname() + ",");
        for (int i = 0; i < Status.getNumberOfStatus(); i++) {
            this.cBStatus.addItem(Status.whichStatus(i));
        }
        this.cBStatus.setSelectedIndex(user.getStatus());
        this.lbHi.setForeground(Color.WHITE);
        this.lbHowYouRFeeling.setForeground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lbHi = new javax.swing.JLabel();
        lbHowYouRFeeling = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cBStatus = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);

        jPanel3.setOpaque(false);

        lbHi.setFont(OurFonts.getTitleFont(36f)
        );
        lbHi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbHi.setText("Hi <user>,");

        lbHowYouRFeeling.setFont(OurFonts.getTitleFont(18f)
        );
        lbHowYouRFeeling.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHowYouRFeeling.setText("How are you feeling today??");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbHi, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHowYouRFeeling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbHi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbHowYouRFeeling, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setOpaque(false);

        cBStatus.setFont(OurFonts.getTextFont(14f)
        );
        cBStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cBStatusItemStateChanged(evt);
            }
        });
        cBStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBStatusActionPerformed(evt);
            }
        });
        cBStatus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cBStatusFocusLost(evt);
            }
        });
        jPanel1.add(cBStatus);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/botao_refresh.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cBStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cBStatusItemStateChanged


    }//GEN-LAST:event_cBStatusItemStateChanged

    private void cBStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBStatusActionPerformed

    private void cBStatusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cBStatusFocusLost
    //    GlobalClient.gui.changeStatus(this.cBStatus.getSelectedIndex());
        ////////////////////////

    }//GEN-LAST:event_cBStatusFocusLost

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        GlobalClient.gui.changeStatus(this.cBStatus.getSelectedIndex());        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/botao_refresh.png"))); // NOI18N
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/botao_refresh_clicked.png"))); // NOI18N
    }//GEN-LAST:event_jLabel1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cBStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbHi;
    private javax.swing.JLabel lbHowYouRFeeling;
    // End of variables declaration//GEN-END:variables
}
