/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import corecliente.GlobalClient;

/**
 *
 * @author Geeo
 */
public class MessageFilePanel extends javax.swing.JPanel {
    private long file_id;

    /**
     * Creates new form MessageFilePanel
     */
    public MessageFilePanel() {
        initComponents();
    }

    public MessageFilePanel(String fileName, String usuario, String hora, long file_id) {
        initComponents();
        this.btFileDownload.setText(fileName);
        this.lbNameUser.setText(usuario);
        this.lbHora.setText(hora);
        this.file_id = file_id;
    }

    public long getFile_id() {
        return file_id;
    }

    public void setFile_id(long file_id) {
        this.file_id = file_id;
    }


/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNameUser = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        lbHora1 = new javax.swing.JLabel();
        btFileDownload = new javax.swing.JButton();

        lbNameUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNameUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNameUser.setText("<user>");

        lbHora.setText("Hora");

        lbHora1.setText("Sent a file:");

        btFileDownload.setText("Download");
        btFileDownload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btFileDownloadMouseClicked(evt);
            }
        });
        btFileDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFileDownloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNameUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbHora))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btFileDownload, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHora)
                    .addComponent(lbNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHora1)
                    .addComponent(btFileDownload)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btFileDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFileDownloadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFileDownloadActionPerformed

    private void btFileDownloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFileDownloadMouseClicked
        System.out.println("Entrou no mouse clicked");
        GlobalClient.core.startDownload(file_id);
    }//GEN-LAST:event_btFileDownloadMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFileDownload;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbHora1;
    private javax.swing.JLabel lbNameUser;
    // End of variables declaration//GEN-END:variables
}
